add IAM role Cloud Run Job in test project to use Doc AI Processor in central cicd project.
Reduce the steps so I can run just the functional test with subsitution from Cloud Build

diff --git a/build/int.cloudbuild.yaml b/build/int.cloudbuild.yaml
--- a/build/int.cloudbuild.yaml
+++ b/build/int.cloudbuild.yaml
@@ -15,53 +15,53 @@
 ---
 timeout: 7200s
 steps:
-  - id: prepare
-    name: "${_BUILDER_IMAGE_NAME}:${_BUILDER_IMAGE_TAG}"
-    entrypoint: /bin/bash
-    args:
-      - "-e"
-      - "-x"
-      - "-c"
-      - >- # folded text - replace newlines with spaces - each command needs to be separated by ';'
-        gcloud projects create ${_TEST_PROJECT_ID} --folder ${_FOLDER_ID} ;
-        sleep 10 ;
-        trap "gcloud projects delete ${_TEST_PROJECT_ID} --quiet " ERR ;
-        gcloud billing projects link ${_TEST_PROJECT_ID} --billing-account=${_BILLING_ACCOUNT} ;
+  #  - id: prepare
+  #    name: "${_BUILDER_IMAGE_NAME}:${_BUILDER_IMAGE_TAG}"
+  #    entrypoint: /bin/bash
+  #    args:
+  #      - "-e"
+  #      - "-x"
+  #      - "-c"
+  #      - >- # folded text - replace newlines with spaces - each command needs to be separated by ';'
+  #        gcloud projects create ${_TEST_PROJECT_ID} --folder ${_FOLDER_ID} ;
+  #        sleep 10 ;
+  #        trap "gcloud projects delete ${_TEST_PROJECT_ID} --quiet " ERR ;
+  #        gcloud billing projects link ${_TEST_PROJECT_ID} --billing-account=${_BILLING_ACCOUNT} ;
 
-  - id: pre_tf_setup
-    name: "${_BUILDER_IMAGE_NAME}:${_BUILDER_IMAGE_TAG}"
-    entrypoint: /bin/bash
-    args:
-      - "-x"
-      - "-c"
-      - >- # folded text - replace newlines with spaces - each command needs to be separated by ';'
-        export PROJECT_ID=${_TEST_PROJECT_ID};
-        sample-deployments/composer-orchestrated-process/scripts/pre_tf_setup.sh;
-    env:
-      - "REGION=${_REGION}"
-      - "IAP_ADMIN_ACCOUNT=${_IAP_SUPPORT_EMAIL}"
+  #  - id: pre_tf_setup
+  #    name: "${_BUILDER_IMAGE_NAME}:${_BUILDER_IMAGE_TAG}"
+  #    entrypoint: /bin/bash
+  #    args:
+  #      - "-x"
+  #      - "-c"
+  #      - >- # folded text - replace newlines with spaces - each command needs to be separated by ';'
+  #        export PROJECT_ID=${_TEST_PROJECT_ID};
+  #        sample-deployments/composer-orchestrated-process/scripts/pre_tf_setup.sh;
+  #    env:
+  #      - "REGION=${_REGION}"
+  #      - "IAP_ADMIN_ACCOUNT=${_IAP_SUPPORT_EMAIL}"#
 
-  - id: terratest
-    name: "${_BUILDER_IMAGE_NAME}:${_BUILDER_IMAGE_TAG}"
-    args:
-      - "-e"
-      - "-x"
-      - "-c"
-      - >-
-        export PROJECT_ID=${_TEST_PROJECT_ID};
-        gcloud config set auth/impersonate_service_account ${_DEPLOYER_SA};
-        (cd build/test && make e2e-test);
-        gcloud config unset auth/impersonate_service_account;
-    entrypoint: /bin/bash
-    env:
-      - "REGION=${_REGION}"
-      - "DOC_AI_LOCATION=${_DOC_AI_LOCATION}"
-      - "VERTEX_AI_DATA_STORE_REGION=${_VERTEX_AI_DATA_STORE_REGION}"
-      - "IAP_ACCESS_DOMAINS=${_IAP_ACCESS_DOMAINS}"
-      - "WEB_UI_DOMAINS=${_WEB_UI_DOMAINS}"
-      - "GCLOUD_TF_DOWNLOAD=never"
-      - "CUSTOM_CLASSIFIER_ID=${_CUSTOM_CLASSIFIER_ID}"
-      - "GOOGLE_IMPERSONATE_SERVICE_ACCOUNT=${_DEPLOYER_SA}"
+  #  - id: terratest
+  #    name: "${_BUILDER_IMAGE_NAME}:${_BUILDER_IMAGE_TAG}"
+  #    args:
+  #      - "-e"
+  #      - "-x"
+  #      - "-c"
+  #      - >-
+  #        export PROJECT_ID=${_TEST_PROJECT_ID};
+  #        gcloud config set auth/impersonate_service_account ${_DEPLOYER_SA};
+  #        (cd build/test && make e2e-test);
+  #        gcloud config unset auth/impersonate_service_account;
+  #    entrypoint: /bin/bash
+  #    env:
+  #      - "REGION=${_REGION}"
+  #      - "DOC_AI_LOCATION=${_DOC_AI_LOCATION}"
+  #      - "VERTEX_AI_DATA_STORE_REGION=${_VERTEX_AI_DATA_STORE_REGION}"
+  #      - "IAP_ACCESS_DOMAINS=${_IAP_ACCESS_DOMAINS}"
+  #      - "WEB_UI_DOMAINS=${_WEB_UI_DOMAINS}"
+  #      - "GCLOUD_TF_DOWNLOAD=never"
+  #      - "CUSTOM_CLASSIFIER_ID=${_CUSTOM_CLASSIFIER_ID}"
+  #      - "GOOGLE_IMPERSONATE_SERVICE_ACCOUNT=${_DEPLOYER_SA}"
 
   - id: functional
     name: "${_BUILDER_IMAGE_NAME}:${_BUILDER_IMAGE_TAG}"
@@ -70,17 +70,18 @@ steps:
       - "-c"
       - >-
         export PROJECT_ID=${_TEST_PROJECT_ID};
+        echo "ingest test documents...";
         build/test/ingest_test_docs.sh;
+        echo "grant IAM role for pretrained classifier in different project...";
+        gcloud projects add-iam-policy-binding $CICD_PROJECT_ID --member='serviceAccount:eks-doc-classifier@$TEST_PROJECT_ID.iam.gserviceaccount.com' --role='roles/documentai.apiUser';
         echo "sleep to allow DAGs to fully propagate to Composer...";
         sleep 180;
-        echo "validate that DAGs have fully propaged to Composer...";
-        gcloud composer environments run dpu-composer --project=${_TEST_PROJECT_ID} --location=us-central1 dags list;
+        echo "validate that DAGs have fully propagated to Composer...";
+        gcloud composer environments run dpu-composer --project=${_TEST_PROJECT_ID} --location=$LOCATION dags list;
         sample-deployments/composer-orchestrated-process/scripts/trigger_workflow.sh;
         echo "sleep to allow Workflow to complete...";
         sleep 1800;
         (cd /workspace/build/test && make functional-test);
-        # sample-deployments/composer-orchestrated-process/scripts/delete_doc.sh;
-        # sample-deployments/composer-orchestrated-process/scripts/reset_datastore.sh;
     entrypoint: /bin/bash
     env:
       - "CICD_PROJECT_ID=${PROJECT_ID}"
@@ -89,15 +90,15 @@ steps:
       - "COMPOSER_ENV_NAME=dpu-composer"
       - "DAG_ID=run_docs_processing"
 
-  - id: cleanup
-    name: "${_BUILDER_IMAGE_NAME}:${_BUILDER_IMAGE_TAG}"
-    args:
-      - "-e"
-      - "-x"
-      - "-c"
-      - >-
-        gcloud projects delete ${_TEST_PROJECT_ID} --quiet
-    entrypoint: /bin/bash
+#  - id: cleanup
+#    name: "${_BUILDER_IMAGE_NAME}:${_BUILDER_IMAGE_TAG}"
+#    args:
+#      - "-e"
+#      - "-x"
+#      - "-c"
+#      - >-
+#        gcloud projects delete ${_TEST_PROJECT_ID} --quiet
+#    entrypoint: /bin/bash
 
 tags:
   - "ci"
@@ -107,7 +108,8 @@ options:
   logging: CLOUD_LOGGING_ONLY
 
 substitutions:
-  _TEST_PROJECT_ID: "eks-int-${SHORT_SHA}"
+  #_TEST_PROJECT_ID: "eks-int-${SHORT_SHA}"
+  _TEST_PROJECT_ID: "eks-int-eks-int-8523ca0"
   _DEPLOYER_SA: "deployer@${_TEST_PROJECT_ID}.iam.gserviceaccount.com"
   _REGION: "us-central1"
   _DOC_AI_LOCATION: "us"
